name: gem
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.3"
          rustup-toolchain: stable
          bundler-cache: true
          cargo-cache: true
          working-directory: gems/beagle-turso
      - run: bundle install
        working-directory: gems/beagle-turso
      - run: bundle exec rake compile
        working-directory: gems/beagle-turso
      - run: bundle exec rspec
        working-directory: gems/beagle-turso
